version: "3"

services:
  cloudservice:
    container_name: cloudservice
    build:
      context: .
    ports:
      - "5500:5500"
    depends_on:
      - database_postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database_postgres:5432/cloudservice
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_FLYWAY_URL: jdbc:postgresql://database_postgres:5432/cloudservice

  database_postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: cloudservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"