version: "3"

services:
  cloudservice:
    container_name: cloudservice
    build:
      context: .
    ports:
      - "5505:5500"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/cloudservice
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_FLYWAY_URL: jdbc:postgresql://database:5432/cloudservice

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: cloudservice
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"

volumes:
  db: